#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed n where n is a number entered by user, find the sum of the even-valued terms.

def sys
calc(n):
    #TODO

if __name__ == '__main__':
    #Accept user input and call calc()
    #TODO
    sys.exit(0)


